# Conditions and Conditional Statements

## Conditions

In [1]:
print(2 > 3)

False


Kode di atas menggunakan operator perbandingan (>). Pada baris ini, kita memeriksa apakah angka 2 lebih besar dari angka 3. Jika pernyataan ini benar, maka hasilnya akan True, dan jika salah, hasilnya akan False.

Dalam kasus ini, karena 2 tidak lebih besar dari 3, maka output yang akan ditampilkan adalah:

False

var_one = 1
var_two = 2

print(var_one < 1)
print(var_two >= var_one)

1. var_one is assigned the value 1, and var_two is assigned the value 2.
2. The first print statement checks whether var_one is less than 1. Since 1 is not less than 1, the result will be False.
3. The second print statement compares whether var_two is greater than or equal to var_one. Since 2 is greater than 1, the result will be True.

## Conditional statements

### "if" statements

In [3]:
def evaluate_temp(temp):
    # Set an initial message
    message = "Normal temperature."
    # Update value of message only if temperature greater than 38
    if temp > 38:
        message = "Fever!"
    return message

This function, evaluate_temp, takes a single argument, temp, which presumably represents a temperature value. Here’s how it works:
1. An initial message is set to “Normal temperature.”
2. The function then checks whether the input temperature (temp) is greater than 38.
3. If the temperature is greater than 38, the message is updated to “Fever!” Otherwise, it remains “Normal temperature.”
4. Finally, the function returns the updated message.

In [4]:
print(evaluate_temp(37))

Normal temperature.


The output of the function evaluate_temp(37) will be:

“Normal temperature.”

In [5]:
print(evaluate_temp(39))

Fever!


### "if ... else" statements¶

The output of the function evaluate_temp(39) will be:

“Fever!”

In [6]:
def evaluate_temp_with_else(temp):
    if temp > 38:
        message = "Fever!"
    else:
        message = "Normal temperature."
    return message

Fungsi evaluate_temp_with_else yang diberikan memiliki dua cabang kondisi. Berikut adalah penjelasan lebih lanjut:
1. Pertama, fungsi memeriksa apakah suhu (temp) lebih besar dari 38.
2. Jika suhu lebih besar dari 38, maka pesan yang dihasilkan adalah “Fever!”.
3. Jika tidak, pesan yang dihasilkan adalah “Normal temperature.”

In [8]:
print(evaluate_temp_with_else(37))

Normal temperature.


### "if ... elif ... else" statements

Output dari fungsi evaluate_temp_with_else(37) adalah:

“Normal temperature.”

In [9]:
def evaluate_temp_with_elif(temp):
    if temp > 38:
        message = "Fever!"
    elif temp > 35:
        message = "Normal temperature."
    else:
        message = "Low temperature."
    return message

Fungsi evaluate_temp_with_elif mengevaluasi suhu berdasarkan tiga kondisi:
1. Jika suhu (temp) lebih besar dari 38, maka pesan diatur menjadi “Fever!”.
2. Jika suhu tidak lebih besar dari 38, tetapi masih lebih besar dari 35, maka pesan diatur menjadi “Normal temperature.”
3. Jika tidak (jika suhu 35 atau lebih rendah), maka pesan diatur menjadi “Low temperature.”

In [10]:
evaluate_temp_with_elif(36)

'Normal temperature.'

Hasil dari fungsi evaluate_temp_with_elif(36) adalah:

“Normal temperature.”

In [11]:
evaluate_temp_with_elif(34)

'Low temperature.'

Hasil dari fungsi evaluate_temp_with_elif(34) adalah:

“Low temperature.”

## Example - Calculations

In [12]:
def get_taxes(earnings):
    if earnings < 12000:
        tax_owed = .25 * earnings
    else:
        tax_owed = .30 * earnings
    return tax_owed

Fungsi get_taxes yang diberikan menghitung jumlah pajak berdasarkan aturan berikut:
1. Jika earnings kurang dari `$12.000`, maka tarif pajak adalah 25%.
2. Jika tidak (jika earnings lebih besar dari atau sama dengan `$12.000`), maka tarif pajak adalah 30%.

In [13]:
ana_taxes = get_taxes(9000)
bob_taxes = get_taxes(15000)

print(ana_taxes)
print(bob_taxes)

2250.0
4500.0


Ana akan membayar pajak sebesar `$2,250.00`, sedangkan Bob akan membayar pajak sebesar `$4,500.00`.

## Example - Multiple "elif" statements

In [14]:
def get_dose(weight):
    # Dosage is 1.25 ml for anyone under 5.2 kg
    if weight < 5.2:
        dose = 1.25
    elif weight < 7.9:
        dose = 2.5
    elif weight < 10.4:
        dose = 3.75
    elif weight < 15.9:
        dose = 5
    elif weight < 21.2:
        dose = 7.5
    # Dosage is 10 ml for anyone 21.2 kg or over
    else:
        dose = 10
    return dose

Berikut adalah penjelasan dari fungsi get_dose yang Anda berikan:
1. Jika berat badan (weight) kurang dari 5.2 kg, dosis yang diberikan adalah 1.25 ml.
2. Jika berat badan kurang dari 7.9 kg, dosis yang diberikan adalah 2.5 ml.
3. Jika berat badan kurang dari 10.4 kg, dosis yang diberikan adalah 3.75 ml.
4. Jika berat badan kurang dari 15.9 kg, dosis yang diberikan adalah 5 ml.
5. Jika berat badan kurang dari 21.2 kg, dosis yang diberikan adalah 7.5 ml.
6. Jika berat badan 21.2 kg atau lebih, dosis yang diberikan adalah 10 ml.

In [15]:
print(get_dose(12))

5


Dosis yang diberikan untuk berat badan 12 kg adalah 3.75 ml.